"""Optional local LibreDWG bridge, with strict geometry round-trip checks.

Only the simple entities generated by our experimental exporter are accepted.
The temporary DXF adapter omits optional object dictionaries and exchanges
typed object handles to work around LibreDWG 0.14's model-space initializer.
The downloadable DXF is never modified.
"""
import math
import os
import shutil
import subprocess
import tempfile
from pathlib import Path

DEFAULT_TOOLS = Path(__file__).resolve().parents[1] / '.dwg-tools'


def find_tools(folder=None):
    folder = Path(folder or os.environ.get('PO_DWG_TOOLS', DEFAULT_TOOLS))
    suffix = '.exe' if os.name == 'nt' else ''
    found = {}
    for name in ('dxf2dwg', 'dwg2dxf'):
        candidate = folder / (name + suffix)
        command = str(candidate) if candidate.is_file() else shutil.which(name)
        if not command:
            raise RuntimeError('Local DWG tools are missing. Run install_dwg_tools.bat once, or set PO_DWG_TOOLS to a LibreDWG 0.14 tools folder.')
        found[name] = command
    return found


def adapter_dxf(source, output):
    import ezdxf
    doc = ezdxf.readfile(source)
    if doc.dxfversion != 'AC1015':
        raise ValueError('The DWG adapter requires the generated R2000 DXF.')
    model = doc.block_records.get('*Model_Space').dxf.handle.upper()
    lines = Path(source).read_text(encoding=doc.encoding).splitlines()
    if len(lines) % 2:
        raise ValueError('Malformed DXF tag pairs.')
    result, skip = [], False
    for i in range(0, len(lines), 2):
        code, value = int(lines[i]), lines[i+1].strip()
        if code == 0 and value == 'SECTION':
            if i+3 >= len(lines):
                raise ValueError('Truncated DXF section.')
            skip = lines[i+3].strip() in ('OBJECTS', 'CLASSES')
        if not skip:
            # Handle values occur only in these typed groups. Text that happens
            # to equal a hexadecimal handle must remain unchanged.
            if (code in (5, 105, 1005, 480, 481)
                    or 320 <= code <= 369 or 390 <= code <= 399):
                if value.upper() == model:
                    value = '1F'
                elif value.upper() == '1F':
                    value = model
                result.extend((lines[i], value))
            else:
                result.extend(lines[i:i+2])
        if code == 0 and value == 'ENDSEC':
            skip = False
    Path(output).write_text('\n'.join(result) + '\n', encoding=doc.encoding)


def signature(entity):
    """Visible geometry and text, excluding serialization handles/defaults."""
    d = entity.dxf
    kind = entity.dxftype()
    common = [kind, d.layer.casefold(), d.get('linetype', 'BYLAYER').casefold(),
              d.get('color', 256), tuple(d.get('extrusion', (0, 0, 1)))]
    fields = {
        'LINE': ('start', 'end'), 'ARC': ('center', 'radius', 'start_angle', 'end_angle'),
        'CIRCLE': ('center', 'radius'), 'SOLID': ('vtx0', 'vtx1', 'vtx2', 'vtx3'),
        'ELLIPSE': ('center', 'major_axis', 'ratio', 'start_param', 'end_param'),
        'TEXT': ('insert', 'text', 'height', 'rotation', 'width', 'oblique',
                 'halign', 'valign', 'text_generation_flag'),
    }
    if kind in fields:
        values = [d.get(key, entity.DXFATTRIBS.get(key).default) for key in fields[kind]]
        if kind == 'TEXT':
            values.append(d.style.casefold())
        return common + values
    if kind == 'SPLINE':
        return common + [d.degree, d.flags & 7, list(entity.control_points),
                         list(entity.knots), list(entity.weights)]
    if kind == 'LWPOLYLINE':
        return common + [entity.closed, d.elevation, list(entity.get_points())]
    if kind == 'HATCH':
        paths = []
        for path in entity.paths:
            edges = []
            for edge in path.edges:
                if edge.type == 1:
                    edges.append(['line', tuple(edge.start), tuple(edge.end)])
                elif edge.type == 2:
                    edges.append(['arc', tuple(edge.center), edge.radius,
                                  edge.start_angle, edge.end_angle, bool(edge.ccw)])
                else:
                    raise ValueError('Unsupported DWG hatch edge.')
            paths.append([path.path_type_flags, edges])
        return common + [d.solid_fill, d.pattern_name, paths]
    raise ValueError('Unsupported DWG validation entity: ' + kind)


def same(a, b):
    if isinstance(a, (int, float)) and isinstance(b, (int, float)):
        return math.isclose(a, b, rel_tol=1e-10, abs_tol=1e-7)
    if isinstance(a, str) or isinstance(b, str):
        return a == b
    if hasattr(a, '__iter__') and hasattr(b, '__iter__'):
        a, b = list(a), list(b)
        return len(a) == len(b) and all(same(x, y) for x, y in zip(a, b))
    return a == b


def validate_roundtrip(source, roundtrip):
    import ezdxf
    original, converted = ezdxf.readfile(source), ezdxf.readfile(roundtrip)
    audit = converted.audit()
    if audit.has_errors or audit.has_fixes:
        raise ValueError('DWG round-trip needed DXF repairs; no DWG was published.')
    if original.units != 4 or converted.units != original.units:
        raise ValueError('DWG round-trip changed millimetre units.')
    before, after = list(original.modelspace()), list(converted.modelspace())
    if len(before) != len(after):
        raise ValueError('DWG round-trip lost or added drawing entities.')
    for index, (a, b) in enumerate(zip(before, after)):
        if not same(signature(a), signature(b)):
            raise ValueError(f'DWG round-trip changed entity {index} ({a.dxftype()}).')
    # Font and centre-line definitions are visible too.
    for style in original.styles:
        other = converted.styles.get(style.dxf.name)
        if style.dxf.font.casefold() != other.dxf.font.casefold():
            raise ValueError('DWG round-trip changed a text font.')
    for line in original.linetypes:
        other = converted.linetypes.get(line.dxf.name)
        if not same(line.pattern_tags.compile(), other.pattern_tags.compile()):
            raise ValueError('DWG round-trip changed a line pattern.')
    return {'entity_count': len(after), 'roundtrip_verified': True, 'units': 'mm',
            'dwg_version': 'R2000', 'validation': 'LibreDWG to DXF plus ezdxf audit and entity comparison',
            'independent_cad_viewer_checked': False}


def write_dwg(source, output, folder=None):
    from core import copy_new
    tools = find_tools(folder)
    output = Path(output)
    if output.exists():
        raise FileExistsError(f'Will not overwrite {output}')
    for tool in tools.values():
        result = subprocess.run([tool, '--version'], capture_output=True, text=True, timeout=10)
        version = result.stdout.splitlines()
        if result.returncode or not version or '0.14' not in version[0].split():
            raise RuntimeError('This DWG bridge requires LibreDWG 0.14.')
    with tempfile.TemporaryDirectory(prefix='drawing-dwg-', dir=output.parent) as temp:
        root = Path(temp)
        adapter, dwg, recovered = root/'adapter.dxf', root/'export.dwg', root/'roundtrip.dxf'
        adapter_dxf(source, adapter)
        for command in ([tools['dxf2dwg'], '-v0', '--as', 'r2000', '-o', str(dwg), str(adapter)],
                        [tools['dwg2dxf'], '-v0', '-o', str(recovered), str(dwg)]):
            result = subprocess.run(command, capture_output=True, text=True, timeout=30)
            if result.returncode:
                raise RuntimeError('Local DWG tool failed: ' + result.stderr.strip()[-1200:])
        if not dwg.is_file() or dwg.read_bytes()[:6] != b'AC1015' or not recovered.is_file():
            raise ValueError('The local tool did not produce a readable R2000 DWG.')
        metrics = validate_roundtrip(source, recovered)
        copy_new(dwg, output)
    return metrics
